version: '3'
services:
    nginx:
        container_name: galoory-nginx
        restart: always
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./ops/nginx/hosts/:/etc/nginx/sites-enabled
            - ./ops/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs/nginx/:/var/log/nginx
            - nfsmountSymfonyGaloory:/var/www/html/symfony
        depends_on:
            - api
        networks:
            - default

    client:
        container_name: galoory-client
        image: node:latest
        networks:
            - default
        tty: true
        volumes:
            - ./vue:/usr/src/galoory
            - galoory_node_modules:/usr/src/galoory/node_modules
        working_dir: /usr/src/galoory
        command: npm run serve
        environment:
            - NODE_ENV=development
        expose:
            - 8080
        ports:
            - 9229:9229
            - 8080:8080
    
    db:
        container_name: galoory-db
        image: postgres:latest
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - default
        environment:
            TZ: Europe/Paris
            POSTGRES_USER: root
            POSTGRES_DB: cacompliance
            POSTGRES_PASSWORD: root

    api:
        container_name: galoory-api
        image: php:7.4-fpm
        command: php-fpm
        build:
            context: ./ops/php
            args:
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        depends_on:
            - db
        working_dir: /var/www/html/symfony
        volumes:
            - "nfsmountSymfonyGaloory:/var/www/html/symfony"
        networks:
            - default
        environment:
            DATABASE_URL: pgsql://root:root@db:5432/galoory
    



volumes:
    galoory_node_modules:
        external: true
    postgres: ~
    nfsmountSymfonyGaloory:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":/System/Volumes/Data${PWD}/symfony"
    