version: '2'
services:
    base-node:
        image: node:latest
        volumes:
            - ./vue:/usr/src/galoory/
            - ./vue/node_modules:/usr/src/galoory/node_modules
        working_dir: /usr/src/galoory/
    install-node:
        extends:
            service: base-node
        command: npm i
    base-php:
        image: php:7.4-fpm
        volumes:
            - ./symfony:/var/www/html/symfony
        working_dir: /var/www/html/symfony
    install-php:
        extends:
            service: base-php
        command: composer install

volumes:
    postgres: ~
