framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_ping_connection
                    - doctrine_close_connection
            event.bus:
                middleware:
                    - validation
                    - doctrine_ping_connection
                    - doctrine_close_connection

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0

        routing:
